---
- hosts: localhost
  tasks:
  - name: task1
    debug: msg="This is task1"
  - name: task2
    debug: msg="This is task2"
    tags: install
  - name: task3
    debug: msg="This is task3"
  - name: task4
    debug: msg="This is task4"
    tags: install
  - name: task5
    debug: msg="This is task5"
    tags:
     - web
     - db
  - name: task6
    debug: msg="This is task6"
    tags:
      - install
      - prod
  - name: task7
    debug: msg="This is task7"
  - name: task8
    debug: msg="This is task8"
