---
- hosts: node4
  tasks:
  - name: task-1
    wait_for:
      path: /tmp/test.log
      search_regex: bash
      timeout: 20
  - name: task-2
    command: /bin/true
  - name: task-3
    command: /bin/true
