---
- name: Install multiple packages
  hosts: all
  tasks:
  - name: Install packages
    #debug: msg="package name:{{item}}"
    apt: name="{{item}}" state=present
    with_items:
    - apache2
    - vim
    - git
    when: ansible_facts["os_family"] == "Debian"
