---
- hosts: localhost
  tasks:
  - set_fact:
      app_info:
        name: "webApp"
        version: "2.4"
        ports: [80,3000,9090]
        frameworks: [FastAPI,Flask,streamlit]
        active: true
  - debug: var=app_info
